export const APSStatusCodes: Record<string, { en: string; ar: string; }> = {
  '00': { en: 'Invalid Request', ar: 'Invalid Request' },
  '01': { en: 'Order Stored', ar: 'Order Stored' },
  '02': { en: 'Authorization Success', ar: 'Authorization Success' },
  '03': { en: 'Authorization Failed', ar: 'Authorization Failed' },
  '04': { en: 'Capture Success', ar: 'Capture Success' },
  '05': { en: 'Capture failed', ar: 'Capture failed' },
  '06': { en: 'Refund Success', ar: 'Refund Success' },
  '07': { en: 'Refund Failed', ar: 'Refund Failed' },
  '08': { en: 'Authorization Voided Successfully', ar: 'Authorization Voided Successfully' },
  '09': { en: 'Authorization Void Failed', ar: 'Authorization Void Failed' },
  '10': { en: 'Incomplete', ar: 'Incomplete' },
  '11': { en: 'Check status Failed', ar: 'Check status Failed' },
  '12': { en: 'Check status success', ar: 'Check status success' },
  '13': { en: 'Purchase Failure', ar: 'Purchase Failure' },
  '14': { en: 'Purchase Success', ar: 'Purchase Success' },
  '15': { en: 'Uncertain Transaction', ar: 'Uncertain Transaction' },
  '17': { en: 'Tokenization failed', ar: 'Tokenization failed' },
  '18': { en: 'Tokenization success', ar: 'Tokenization success' },
  '19': { en: 'Transaction pending', ar: 'Transaction pending' },
  '20': { en: 'On hold', ar: 'On hold' },
  '21': { en: 'SDK Token creation failure', ar: 'SDK Token creation failure' },
  '22': { en: 'SDK Token creation success', ar: 'SDK Token creation success' },
  '23': {
    en: 'Failed to process Digital Wallet service',
    ar: 'Failed to process Digital Wallet service'
  },
  '24': {
    en: 'Digital wallet order processed successfully',
    ar: 'Digital wallet order processed successfully'
  },
  '27': { en: 'Check card balance failed', ar: 'Check card balance failed' },
  '28': { en: 'Check card balance success', ar: 'Check card balance success' },
  '29': { en: 'Redemption failed', ar: 'Redemption failed' },
  '30': { en: 'Redemption success', ar: 'Redemption success' },
  '31': {
    en: 'Reverse Redemption transaction failed',
    ar: 'Reverse Redemption transaction failed'
  },
  '32': {
    en: 'Reverse Redemption transaction success',
    ar: 'Reverse Redemption transaction success'
  },
  '40': { en: 'Transaction In review', ar: 'Transaction In review' },
  '42': { en: 'Currency conversion success', ar: 'Currency conversion success' },
  '43': { en: 'Currency conversion failed', ar: 'Currency conversion failed' },
  '44': { en: '3ds success', ar: '3ds success' },
  '45': { en: '3ds failed', ar: '3ds failed' },
  '46': { en: 'Bill creation success', ar: 'Bill creation success' },
  '47': { en: 'Bill creation failed', ar: 'Bill creation failed' },
  '48': {
    en: 'Generating invoice payment link success',
    ar: 'Generating invoice payment link success'
  },
  '49': {
    en: 'Generating invoice payment link failed',
    ar: 'Generating invoice payment link failed'
  },
  '50': { en: 'Batch file upload successfully', ar: 'Batch file upload successfully' },
  '51': { en: 'Upload batch file failed', ar: 'Upload batch file failed' },
  '52': { en: 'Token created successfully', ar: 'Token created successfully' },
  '53': { en: 'Token creation failed', ar: 'Token creation failed' },
  '54': { en: 'Get Tokens Success', ar: 'Get Tokens Success' },
  '55': { en: 'Get Tokens Failed', ar: 'Get Tokens Failed' },
  '56': { en: 'Reporting Request Success', ar: 'Reporting Request Success' },
  '57': { en: 'Reporting Request Failed', ar: 'Reporting Request Failed' },
  '58': { en: 'Token updated successfully', ar: 'Token updated successfully' },
  '59': { en: 'Token updated failed', ar: 'Token updated failed' },
  '62': { en: 'Get Installment Plans Successfully', ar: 'Get Installment Plans Successfully' },
  '63': { en: 'Get Installment plans Failed', ar: 'Get Installment plans Failed' },
  '66': { en: 'Delete Token Success', ar: 'Delete Token Success' },
  '70': { en: 'Get batch results successfully', ar: 'Get batch results successfully' },
  '71': { en: 'Get batch results failed', ar: 'Get batch results failed' },
  '72': { en: 'Batch processing success', ar: 'Batch processing success' },
  '73': { en: 'Batch processing failed', ar: 'Batch processing failed' },
  '74': { en: 'Bank transfer successfully', ar: 'Bank transfer successfully' },
  '75': { en: 'Bank transfer failed', ar: 'Bank transfer failed' },
  '76': { en: 'Batch validation successfully', ar: 'Batch validation successfully' },
  '77': { en: 'Batch validation failed', ar: 'Batch validation failed' },
  '80': { en: 'Credit card verified successfully', ar: 'Credit card verified successfully' },
  '81': { en: 'Failed to verify credit card', ar: 'Failed to verify credit card' }
};
