name: Build and Submit EAS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install

      - name: Build with EAS
        run: yarn eas build --profile production --platform all

      - name: Submit with EAS if build succeeds
        if: ${{ success() }}
        run: yarn eas submit -p all --latest
